"""
Migration 011: Deep Report v2 Schema

vNext-R3-A: Deep Report v2 - Multi-stage, evidence-backed, chapterized competitive analysis.

This migration adds tables for:
- report_sections: Individual report chapters with metadata
- section_research_packs: Evidence/signed claims binding per section
- section_drafts: Section writing drafts with revision tracking
- report_figures: Chart specifications generated by ChartAgent
- report_tables: Comparison matrices generated by TableAgent
- report_reviews: Deep report reviewer traces
"""

import sqlite3
from pathlib import Path


def migrate(db_path: Path) -> None:
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # 1. report_sections - Individual report chapters
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS report_sections (
            section_id TEXT PRIMARY KEY,
            report_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            section_index INTEGER NOT NULL,
            section_slug TEXT NOT NULL,
            section_title TEXT NOT NULL,
            section_type TEXT NOT NULL DEFAULT 'chapter',
            min_word_count INTEGER NOT NULL DEFAULT 800,
            target_word_count INTEGER NOT NULL DEFAULT 1200,
            status TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'research_pack_ready', 'drafting', 'draft_complete', 
                                 'reviewing', 'review_complete', 'revision_requested', 'final', 'skipped')),
            depth_score REAL,
            evidence_count INTEGER NOT NULL DEFAULT 0,
            claim_count INTEGER NOT NULL DEFAULT 0,
            word_count INTEGER NOT NULL DEFAULT 0,
            revision_count INTEGER NOT NULL DEFAULT 0,
            writing_requirements_json TEXT NOT NULL DEFAULT '{}',
            review_notes TEXT,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (report_id) REFERENCES reports(report_id),
            FOREIGN KEY (run_id) REFERENCES runs(run_id)
        )
    """)
    
    # 2. section_research_packs - Evidence/signed claims binding per section
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS section_research_packs (
            pack_id TEXT PRIMARY KEY,
            section_id TEXT NOT NULL,
            report_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            section_question TEXT NOT NULL,
            required_dimensions_json TEXT NOT NULL DEFAULT '[]',
            evidence_items_json TEXT NOT NULL DEFAULT '[]',
            facts_json TEXT NOT NULL DEFAULT '[]',
            candidate_claims_json TEXT NOT NULL DEFAULT '[]',
            signed_claims_json TEXT NOT NULL DEFAULT '[]',
            comparison_points_json TEXT NOT NULL DEFAULT '[]',
            missing_information_json TEXT NOT NULL DEFAULT '[]',
            risk_notes_json TEXT NOT NULL DEFAULT '[]',
            recommended_tables_json TEXT NOT NULL DEFAULT '[]',
            status TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'building', 'ready', 'insufficient', 'failed')),
            evidence_coverage_rate REAL NOT NULL DEFAULT 0.0,
            confidence_level TEXT DEFAULT 'medium'
                CHECK (confidence_level IN ('low', 'medium', 'high')),
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (section_id) REFERENCES report_sections(section_id),
            FOREIGN KEY (report_id) REFERENCES reports(report_id),
            FOREIGN KEY (run_id) REFERENCES runs(run_id)
        )
    """)
    
    # 3. section_drafts - Section writing drafts with revision tracking
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS section_drafts (
            draft_id TEXT PRIMARY KEY,
            section_id TEXT NOT NULL,
            report_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            draft_index INTEGER NOT NULL DEFAULT 1,
            draft_type TEXT NOT NULL DEFAULT 'initial'
                CHECK (draft_type IN ('initial', 'revision', 'final')),
            content_markdown TEXT NOT NULL,
            content_html TEXT,
            trigger_type TEXT NOT NULL DEFAULT 'automatic'
                CHECK (trigger_type IN ('automatic', 'rework', 'human_edit')),
            rework_issue_id TEXT,
            review_feedback TEXT,
            approved INTEGER NOT NULL DEFAULT 0,
            word_count INTEGER NOT NULL DEFAULT 0,
            quality_score REAL,
            issues_json TEXT NOT NULL DEFAULT '[]',
            created_by_agent TEXT NOT NULL DEFAULT 'section_writer',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (section_id) REFERENCES report_sections(section_id),
            FOREIGN KEY (report_id) REFERENCES reports(report_id),
            FOREIGN KEY (run_id) REFERENCES runs(run_id)
        )
    """)
    
    # 4. report_figures - Chart specifications generated by ChartAgent
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS report_figures (
            figure_id TEXT PRIMARY KEY,
            report_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            figure_type TEXT NOT NULL
                CHECK (figure_type IN ('swot_card', 'positioning_map', 'comparison_chart', 
                                      'evidence_strength', 'recommendation_card', 'timeline', 'other')),
            figure_title TEXT NOT NULL,
            figure_description TEXT,
            chart_spec_json TEXT NOT NULL DEFAULT '{}',
            chart_data_json TEXT NOT NULL DEFAULT '{}',
            section_id TEXT,
            target_position TEXT,
            width INTEGER DEFAULT 800,
            height INTEGER DEFAULT 600,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (report_id) REFERENCES reports(report_id),
            FOREIGN KEY (run_id) REFERENCES runs(run_id),
            FOREIGN KEY (section_id) REFERENCES report_sections(section_id)
        )
    """)
    
    # 5. report_tables - Comparison matrices generated by TableAgent
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS report_tables (
            table_id TEXT PRIMARY KEY,
            report_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            table_type TEXT NOT NULL
                CHECK (table_type IN ('feature_matrix', 'pricing_matrix', 'enterprise_matrix',
                                      'user_scenario_matrix', 'ecosystem_matrix', 'swot_matrix',
                                      'opportunity_risk_matrix', 'competitor_overview', 'other')),
            table_title TEXT NOT NULL,
            table_description TEXT,
            headers_json TEXT NOT NULL DEFAULT '[]',
            rows_json TEXT NOT NULL DEFAULT '[]',
            cells_json TEXT NOT NULL DEFAULT '{}',
            section_id TEXT,
            target_position TEXT,
            evidence_binding_json TEXT NOT NULL DEFAULT '{}',
            interpretation TEXT,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (report_id) REFERENCES reports(report_id),
            FOREIGN KEY (run_id) REFERENCES runs(run_id),
            FOREIGN KEY (section_id) REFERENCES report_sections(section_id)
        )
    """)
    
    # 6. report_reviews - Deep report reviewer traces
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS report_reviews (
            review_id TEXT PRIMARY KEY,
            report_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            review_type TEXT NOT NULL DEFAULT 'final'
                CHECK (review_type IN ('outline', 'section', 'final', 'quality_gate')),
            target_id TEXT,
            target_type TEXT,
            reviewer_agent TEXT NOT NULL DEFAULT 'report_reviewer',
            overall_score REAL,
            depth_score REAL,
            evidence_score REAL,
            business_value_score REAL,
            status TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'in_progress', 'pass', 'fail', 'rework_required')),
            issues_json TEXT NOT NULL DEFAULT '[]',
            suggestions_json TEXT NOT NULL DEFAULT '[]',
            rework_instruction TEXT,
            approved INTEGER NOT NULL DEFAULT 0,
            reviewer_notes TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (report_id) REFERENCES reports(report_id),
            FOREIGN KEY (run_id) REFERENCES runs(run_id)
        )
    """)
    
    # Create indexes for performance
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_report_sections_report_id ON report_sections(report_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_report_sections_run_id ON report_sections(run_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_section_packs_section_id ON section_research_packs(section_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_section_drafts_section_id ON section_drafts(section_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_report_figures_report_id ON report_figures(report_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_report_tables_report_id ON report_tables(report_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_report_reviews_report_id ON report_reviews(report_id)")
    
    conn.commit()
    conn.close()
    print("Migration 011: Deep Report v2 Schema completed")
