"""Re-generate markdown report files from database spans."""
from __future__ import annotations

import argparse
import json
import sqlite3
from datetime import datetime
from pathlib import Path


def _safe_parse_json(value, default):
    if not value:
        return default
    try:
        return json.loads(value) if isinstance(value, str) else value
    except Exception:
        return default


def _build_markdown(title: str, spans: list[dict], quality_summary: dict, report_status: str) -> str:
    lines = [
        f"# {title}\n",
        f"**Status:** {report_status}\n",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n",
    ]

    qs = quality_summary or {}
    claim_count = qs.get("claim_count", 0)
    coverage = qs.get("evidence_coverage_rate", 0.0)
    unsupported = qs.get("unsupported_claim_count", 0)
    lines.append(
        f"\n**Quality Summary:** "
        f"{claim_count} claims, {coverage:.0%} evidence coverage, "
        f"{unsupported} unsupported\n"
    )
    lines.append("\n---\n")

    if not spans:
        lines.append("\n*No report sections available.*\n")
        return "".join(lines)

    for idx, span in enumerate(spans, 1):
        sec_title = span.get("section_title", f"Section {idx}")
        content = (span.get("text") or "").strip()
        # Avoid double heading if content already starts with ##
        if content.startswith("## "):
            lines.append(f"\n{content}\n")
        else:
            lines.append(f"\n## {sec_title}\n\n{content}\n")

        claim_ids = span.get("claim_ids", [])
        evidence_ids = span.get("evidence_ids", [])
        if claim_ids:
            lines.append(f"*Claims: {len(claim_ids)} | Evidence: {len(evidence_ids)}*\n")
        unsupported_flag = span.get("unsupported_flag", 0)
        if unsupported_flag:
            lines.append("> ⚠️ This section contains unsupported claims.\n")

    lines.append("\n---\n")
    lines.append("*Report generated by ProductInsight Agent.*\n")
    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate markdown report from database")
    parser.add_argument(
        "--run-id",
        default="run_demo_ai_agent_001",
        help="Run ID to regenerate (default: run_demo_ai_agent_001)",
    )
    parser.add_argument(
        "--db",
        default="data/productinsight.db",
        help="Path to SQLite database",
    )
    args = parser.parse_args()

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"Database not found: {db_path}")
        return

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    report = conn.execute(
        "SELECT * FROM reports WHERE run_id = ? ORDER BY created_at DESC LIMIT 1",
        (args.run_id,),
    ).fetchone()

    if not report:
        print(f"No report found for run_id={args.run_id}")
        conn.close()
        return

    report_id = report["report_id"]
    spans_rows = conn.execute(
        "SELECT * FROM report_spans WHERE report_id = ? ORDER BY section_id, span_id",
        (report_id,),
    ).fetchall()
    conn.close()

    spans = []
    for row in spans_rows:
        span = dict(row)
        span["claim_ids"] = _safe_parse_json(span.get("claim_ids_json"), [])
        span["evidence_ids"] = _safe_parse_json(span.get("evidence_ids_json"), [])
        spans.append(span)

    quality_summary = _safe_parse_json(report["quality_summary_json"], {})

    md_content = _build_markdown(
        title=report["title"],
        spans=spans,
        quality_summary=quality_summary,
        report_status=report["report_status"],
    )

    # Write to the expected path
    md_path = Path("data/reports") / f"{report_id}.md"
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(md_content, encoding="utf-8")

    print(f"Regenerated: {md_path} ({len(md_content)} bytes, {len(spans)} sections)")
    print(f"  Status: {report['report_status']}")
    print(f"  Quality: {quality_summary.get('claim_count', 0)} claims, "
          f"{quality_summary.get('evidence_coverage_rate', 0):.0%} coverage")


if __name__ == "__main__":
    main()
